version: "3.3"
services:
  # MySQL
  database-mysql:
    image: mysql:5.7.26
    restart: always
    environment:
      MYSQL_USER: mybooks
      MYSQL_PASSWORD: mybooks
      MYSQL_DATABASE: mybooks
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mybooks_data:/data/mysql
    ports:
      - "3302:3306"

# Volumes
volumes:
  mybooks_data: